import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Adminnavbar from "@/components/Adminnavbar";
import Adminsidebar from "@/components/Adminsidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
          <Adminnavbar />
          <div className="flex">
            <Adminsidebar />
            <div className="flex-1 px-4 py 10 md:px-10 h-[calc(100vh-64px)] overflow-y-auto">
              {children}
            </div>
          </div>
        </>
      </body>
    </html>
  );
}
